publish:
  whoami: asf-site

notifications:
  commits:      commits@hive.apache.org
  issues:       gitbox@hive.apache.org
  pullrequests: gitbox@hive.apache.org
  jira_options: link label

github:
  description: "Apache Hive Website"
  homepage: https://hive.apache.org/
  features:
    wiki: false
    issues: false
    projects: false
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
